// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SwiftUI_Lily5",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "SwiftUI_Lily5",
            targets: ["AppModule"],
            bundleIdentifier: "jp.co.wdkk.SwiftUI-Lily5",
            teamIdentifier: "N6DRT9P33S",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .education
        )
    ],
    dependencies: [
        .package(url: "https://github.com/wdkk/LilySwiftForPlayground.git", "4.9.5"..<"5.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "LilySwiftForPlayground", package: "LilySwiftForPlayground")
            ],
            path: "."
        )
    ]
)
